package com.example.boardgamesapp.model

data class Cafe(
    var id: Int,
    val poi: String,
    val nameNl: String,
    val nameEn: String,
    val nameFr: String,
    val nameDe: String,
    val nameEs: String,
    val descriptionNl: String,
    val descriptionEn: String,
    val descriptionFr: String,
    val descriptionDe: String,
    val descriptionEs: String,
    val url: String,
    val modified: String,
    val catnameNl: String,
    val catnameEn: String,
    val catnameFr: String,
    val catnameDe: String,
    val catnameEs: String,
    val ctcname: String,
    val address: String,
    val postal: String,
    val local: String,
    val icon: String,
    val type: String,
    val symbol: String,
    val identifier: Int,
    val geoPoint: List<Double>
)
